### ISSUE TITLE
Translate: cdi-integration.adoc.po

### ISSUE THREAD

**Issue by vandrep** [quarkusio/pt.quarkus.io#108]

**Comment by vandrep** [comment]
@gastaldi , estou sofrendo um pouco com as traduções aqui... Existe boas práticas sobre como traduzir termos mais técnicos, mas nem tão técnicos assim? 😆 

Um exemplo: "scope". Venho traduzindo como escopo tranquilamente até encontrar um trecho que diz "Bean defining annotations are declared on the class-level and include scopes, stereotypes and `@Interceptor`." . Fiquei um tempo quebrando a cabeça se, já que estou traduzindo scope, deveria traduzir o stereotype também!

No geral tento aceitar um formato e seguir em frente para não travar muito, mas se tiver um jeito mais aceito de lidar com essas nuances acredito que consigo ir mais rápido.

**Comment by gastaldi** [comment]
Opa, sim, nesse caso estereótipos é válido, já que se refere ao conceito, e não à anotação em si
