### ISSUE TITLE
Translation: virtual-threads.adoc.po

### ISSUE THREAD

**Issue by brunolellis** [quarkusio/pt.quarkus.io#15]
Hi!
I am working on `virtual-threads.adoc.po` guide.

@gastaldi are there any recommendation about translating "carrier thread", "pinning" and terms like that to Portuguese? Just use the English term?

I think it might be easier to learn when you read the original term, like "carrier thread" instead of "thread de transporte", "thread de suporte"...

**Comment by gastaldi** [comment]
Sure, using the English term is fine in this case
