### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by vandrep** [quarkusio/pt.quarkus.io#157]
Hello @gastaldi ! I noticed that security-openid-connect-dev-services.adoc.po is missing almost all initial translations. Is there a way to fill it up, deepl way?

**Comment by gastaldi** [comment]
I believe we already do that once a month automatically, but @ynojima may confirm

**Comment by ynojima** [comment]
The machine-translation run once every weeks, but it seems recent two execution failed.
Hopefully the execution in the next month will succeed.
I pushed results of machine-translation run locally. https://github.com/quarkusio/pt.quarkus.io/pull/160

**Comment by vandrep** [comment]
It seems that 1519d88dc588521d41d4edf838d144fb89fd7db8 fixed it.
