### ISSUE TITLE
Translate: Guides > Security vulnerability detection

### ISSUE THREAD

**Issue by alvescamila87** [quarkusio/pt.quarkus.io#172]
Translate: Guides > Security vulnerability detection

**Comment by codespearhead** [comment]
Can you open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and [link this issue to it](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)? Because it's currently not easy to check how it's coming along.

**Comment by alvescamila87** [comment]
Branch merged https://github.com/quarkusio/pt.quarkus.io/pull/186

**Comment by alvescamila87** [comment]
Branch merged https://github.com/quarkusio/pt.quarkus.io/pull/186
