### ISSUE TITLE
Translate: YAML CONFIGURATION

### ISSUE THREAD

**Issue by ArthurGB80** [quarkusio/pt.quarkus.io#178]
Hello Everyone! 

That is my first contribution! I hope to do a good job for all user quarkus.

The file is config-yaml.adoc.po.

**Comment by codespearhead** [comment]
Can you open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and [link this issue to it](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)? Because it's currently not easy to check how it's coming along.
