### ISSUE TITLE
Translation: redis-dev-services

### ISSUE THREAD

**Issue by dellamas** [quarkusio/pt.quarkus.io#20]
Hello everyone,

I would like to inform you that I am working on the translation of the file:
redis-dev-services

**Comment by vandrep** [comment]
Hello @dellamas ! I just finished the translation and stumbled upon your isse. Can I pull mine?

**Comment by dellamas** [comment]
Hi @vandrep , yes you can translate. I'll work on another one, you can complete this one without any problems. Thank you very much for your collaboration!
