### ISSUE TITLE
Translation: liquibase.adoc

### ISSUE THREAD

**Issue by luanbrdev** [quarkusio/pt.quarkus.io#40]
Hi guys, how are you?

I will work on liquibase.adoc. :smiley:

**Comment by codespearhead** [comment]
Can you open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and [link this issue to it](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)? Because it's currently not easy to check how it's coming along.
