### ISSUE TITLE
 Translate: guides/spring-boot-properties

### ISSUE THREAD

**Issue by CarlosEReis** [quarkusio/pt.quarkus.io#80]
translate: guides/spring-boot-properties
page: [https://pt.quarkus.io/guides/spring-boot-properties](https://pt.quarkus.io/guides/spring-boot-properties)

**Comment by gastaldi** [comment]
Fixed in https://github.com/quarkusio/pt.quarkus.io/commit/2ed098b979e452500e3f45ba97286e63f01b5310
